[package]
name = "alacritty-themes-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dirs = "5.0.1"
include_dir = "0.7.4"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"
tui = "0.19.0"
